services:
  database:
      env_file:
      - .env.test
      build:
        context: .
        dockerfile: docker/Dockerfile.db
      environment:
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_USER=${DATABASE_USERNAME}
        - POSTGRES_DB=${DATABASE_NAME}
      ports:
        - ${DATABASE_PORT}:${DATABASE_PORT}