name: pamagramt

services:
  server:
    restart: always
    env_file:
      - .env.test
    build:
      context: .
      dockerfile: docker/Dockerfile.server
      target: test
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database

  database:
      restart: always
      env_file:
      - .env.test
      build:
        context: .
        dockerfile: docker/Dockerfile.db
      environment:
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_USER=${DATABASE_USERNAME}
        - POSTGRES_DB=${DATABASE_NAME}
      ports:
        - ${DATABASE_PORT}:${DATABASE_PORT}