services:
  server:
    restart: always
    container_name: server
    build:
      context: .
      dockerfile: docker/Dockerfile.server
      target: test
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database

  database:
      restart: always
      container_name: database
      build:
        context: .
        dockerfile: docker/Dockerfile.db
      environment:
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_USER=${DATABASE_USERNAME}
        - POSTGRES_DB=${DATABASE_NAME}
      ports:
        - ${DATABASE_PORT}:${DATABASE_PORT}