name: tests-on-push
run-name: ${{ github.actor }} has pushed commits

on: [push]
jobs:
  run-test-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - run: npm install
      - run: npm run test
