name: tests-on-push
run-name: ${{ github.actor }} has pushed commits

on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: nvmrc=$(cat .nvmrc)
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: $nvmrc
      - run: npm install
      - run: npm run test
