name: tests-on-push
run-name: ${{ github.actor }} has pushed commits

on: [push, pull_request]
jobs:
  run-test-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Instal dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
