name: tests-on-push
run-name: ${{ github.actor }} has pushed commits

on: [push, pull_request]
jobs:
  run-test-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NVMRC }}

      - run: npm install
      - run: npm run test
