name: tests
run-name: ${{ github.actor }} has pushed commits

on: [push]

env:
  # * those variables duplicate from .env.test in order to run docker compose for database
  # TODO find a way to avoid duplication of variables
  DATABASE_HOST: localhost
  DATABASE_PORT: 5432
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_NAME: postgres
 
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose.ci.yml"
          services:
            database
          
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      
      - run: npm ci

      - name: Run tests
        run: npm run test:integration


  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      
      - run: npm ci

      - name: Run tests
        run: npm run test:unit
       
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      
      - run: npm ci

      - name: Run tests
        run: npm run lint
      
