name: tests
run-name: ${{ github.actor }} has pushed commits

on: [push]

env:
  PORT: 8080

  SESSION_TIMEOUT_IN_MS: 60000 # 60 * 1000 :  60seconds
  COOKIE_SECRET: 60000         # 60 * 1000 :  60seconds

  SALT_ROUNDS: 5
  TWILIO_VERIFICATION_SERVICE_ID: VA87131e724d22d0afd1605bfb81177ab5
  TWILIO_AUTH_TOKEN: e7b36e627d7b36e32268c3985d3d16bd
  TWILIO_ACCOUNT_SERVICE_ID: AC664a470e0b6ed0f2ddae44af64c9f16e

  # Database
  DATABASE_HOST: database
  DATABASE_PORT: 5432
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_NAME: postgres
 


jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose.ci.yml"
          services:
            database
          
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      
      - run: npm ci

      - name: Run tests
        run: npm run test:integration


  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      
      - run: npm ci

      - name: Run tests
        run: npm run test:unit
       
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      
      - run: npm ci

      - name: Run tests
        run: npm run lint
      
